"""
ML-based alternatives to signal_engine.generate_signal(): trains classifiers
(one for "would a CALL bought here win", one for "would a PUT bought here
win") on historical data, then uses them to produce the same kind of
CALL/PUT/NO_TRADE decision, so any of them can be dropped into the exact
same backtesting loop as the rule-based engine for an honest comparison.

Three model types supported (MODEL_TYPES below) - Random Forest, Logistic
Regression, and Gradient Boosting (XGBoost) - trained and calibrated the
same rigorous way so the comparison between them is fair, not just between
each and the rule-based engine.

Labels are generated by reusing backtester.simulate_trade - the same
Black-Scholes bracket simulation already validated for the rule-based
backtest - so "did this candle's hypothetical trade win" means exactly the
same thing across every approach.

Important caveat (see PROJECT_STATUS.md): the ~130 cached trading days give
far fewer *independent* examples than the raw candle count suggests, since
candles within a day are highly correlated. Everything here (conservative
hyperparameters, chronological train/test split, thresholds calibrated only
from training data) is chosen to resist overfitting on that small a
dataset - treat any result as a first honest look, not a final verdict.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

from backtester import MIN_DAILY_HISTORY, simulate_trade
from ml_features import FEATURE_NAMES, extract_features
from signal_engine import RSI_PERIOD, RSI_TURN_LOOKBACK, SIGNAL_CUTOFF_TIME, Signal

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = PROJECT_ROOT / "data" / "models"

TRAIN_FRACTION = 0.7  # chronological split - first 70% of days train, last 30% test

ModelType = Literal["random_forest", "logistic_regression", "gradient_boosting"]
MODEL_TYPES: list[ModelType] = ["random_forest", "logistic_regression", "gradient_boosting"]

# Threshold calibration target (see calibrate_threshold): the lowest confidence
# cutoff that reaches this training-set precision with enough samples behind it.
TARGET_PRECISION = 0.70
MIN_CALIBRATION_SAMPLES = 30
DEFAULT_THRESHOLD = 0.5  # fallback if no threshold reaches the target


def _build_estimator(model_type: ModelType):
    if model_type == "random_forest":
        return RandomForestClassifier(
            n_estimators=200,
            max_depth=5,          # kept shallow deliberately - small dataset, resist overfitting
            min_samples_leaf=10,  # require real support behind every leaf's prediction
            random_state=42,
        )
    if model_type == "logistic_regression":
        # Logistic regression needs scaled features (unlike tree models) since our
        # features are on very different scales (RSI 0-100 vs. fib distances ~0.01
        # vs. minutes_since_open ~0-330) - a Pipeline keeps scaling bundled with the model.
        return Pipeline([
            ("scale", StandardScaler()),
            ("model", LogisticRegression(max_iter=1000, random_state=42)),
        ])
    if model_type == "gradient_boosting":
        return XGBClassifier(
            n_estimators=200,
            max_depth=3,          # shallow - gradient boosting overfits small data easily otherwise
            learning_rate=0.05,   # slow learning, more regularized
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric="logloss",
        )
    raise ValueError(f"Unknown model_type: {model_type}")


def build_labeled_dataset(daily_df: pd.DataFrame, intraday_df: pd.DataFrame) -> pd.DataFrame:
    """Walks every cached trading day's candles, computing features + labels
    ("would a CALL/PUT bought here have hit +10% before -10% by EOD")."""
    intraday_df = intraday_df.copy()
    intraday_df["trading_day"] = intraday_df["date"].dt.date

    all_days = sorted(intraday_df["trading_day"].unique())
    full_day_candle_count = intraday_df["trading_day"].value_counts().median()
    complete_days = [d for d in all_days if (intraday_df["trading_day"] == d).sum() >= full_day_candle_count * 0.8]

    rows = []
    start_index = RSI_PERIOD + RSI_TURN_LOOKBACK

    for day in complete_days:
        daily_history = daily_df[daily_df["date"].dt.date < day]
        if len(daily_history) < MIN_DAILY_HISTORY:
            continue

        day_intraday = intraday_df[intraday_df["trading_day"] == day].drop(columns=["trading_day"]).reset_index(drop=True)

        for i in range(start_index, len(day_intraday)):
            timestamp = pd.Timestamp(day_intraday["date"].iloc[i])
            if timestamp.time() > SIGNAL_CUTOFF_TIME:
                break

            features = extract_features(daily_history, day_intraday, i)
            entry_price = day_intraday["close"].iloc[i]
            remaining_intraday = day_intraday[day_intraday["date"] > timestamp]

            call_trade = simulate_trade("CALL", "ml_label", timestamp.to_pydatetime(), entry_price, daily_history, remaining_intraday)
            put_trade = simulate_trade("PUT", "ml_label", timestamp.to_pydatetime(), entry_price, daily_history, remaining_intraday)

            row = dict(features)
            row["date"] = day
            row["call_label"] = int(call_trade.exit_reason == "TARGET")
            row["put_label"] = int(put_trade.exit_reason == "TARGET")
            rows.append(row)

    return pd.DataFrame(rows)


def time_based_split(labeled_df: pd.DataFrame, train_fraction: float = TRAIN_FRACTION) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Chronological split by date - never random, to avoid leaking correlated
    nearby days between train and test."""
    unique_days = sorted(labeled_df["date"].unique())
    split_point = int(len(unique_days) * train_fraction)
    train_days, test_days = set(unique_days[:split_point]), set(unique_days[split_point:])

    train_df = labeled_df[labeled_df["date"].isin(train_days)].reset_index(drop=True)
    test_df = labeled_df[labeled_df["date"].isin(test_days)].reset_index(drop=True)
    return train_df, test_df


def calibrate_threshold(
    probs: np.ndarray,
    labels: pd.Series,
    target_precision: float = TARGET_PRECISION,
    min_samples: int = MIN_CALIBRATION_SAMPLES,
) -> float:
    """Scans candidate thresholds and picks the LOWEST one that reaches
    target_precision with at least min_samples supporting it - using only
    the data passed in (call this with training data only, never test data).
    Falls back to whichever threshold gives the best precision with enough
    samples if the target is never reached. This replaces manually eyeballing
    a precision table by hand for every model type."""
    candidates = []
    for t in np.arange(0.30, 0.85, 0.01):
        mask = probs >= t
        n = mask.sum()
        if n >= min_samples:
            precision = labels[mask].mean()
            candidates.append((round(t, 2), precision, n))

    meeting_target = [c for c in candidates if c[1] >= target_precision]
    if meeting_target:
        return min(meeting_target, key=lambda c: c[0])[0]
    if candidates:
        return max(candidates, key=lambda c: c[1])[0]
    return DEFAULT_THRESHOLD


def train_models(train_df: pd.DataFrame, model_type: ModelType):
    """Returns (call_model, put_model, call_threshold, put_threshold)."""
    X = train_df[FEATURE_NAMES]

    call_model = _build_estimator(model_type).fit(X, train_df["call_label"])
    put_model = _build_estimator(model_type).fit(X, train_df["put_label"])

    call_threshold = calibrate_threshold(call_model.predict_proba(X)[:, 1], train_df["call_label"])
    put_threshold = calibrate_threshold(put_model.predict_proba(X)[:, 1], train_df["put_label"])

    return call_model, put_model, call_threshold, put_threshold


def save_models(model_type: ModelType, call_model, put_model, call_threshold: float, put_threshold: float) -> None:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(call_model, MODELS_DIR / f"call_model_{model_type}.joblib")
    joblib.dump(put_model, MODELS_DIR / f"put_model_{model_type}.joblib")
    joblib.dump({"call": call_threshold, "put": put_threshold}, MODELS_DIR / f"thresholds_{model_type}.joblib")


def load_models(model_type: ModelType):
    call_model = joblib.load(MODELS_DIR / f"call_model_{model_type}.joblib")
    put_model = joblib.load(MODELS_DIR / f"put_model_{model_type}.joblib")
    thresholds = joblib.load(MODELS_DIR / f"thresholds_{model_type}.joblib")
    return call_model, put_model, thresholds["call"], thresholds["put"]


def generate_ml_signal(
    daily_df: pd.DataFrame,
    intraday_df: pd.DataFrame,
    call_model,
    put_model,
    call_threshold: float = DEFAULT_THRESHOLD,
    put_threshold: float = DEFAULT_THRESHOLD,
) -> Signal:
    """Mirrors signal_engine.generate_signal()'s exact interface and
    one-trade-per-day contract, so it can replace it in the same backtesting
    loop unchanged. Works with any model exposing predict_proba (Random
    Forest, Logistic Regression, XGBoost all qualify)."""
    intraday_df = intraday_df.reset_index(drop=True)
    start_index = RSI_PERIOD + RSI_TURN_LOOKBACK

    for i in range(start_index, len(intraday_df)):
        timestamp = pd.Timestamp(intraday_df["date"].iloc[i])
        if timestamp.time() > SIGNAL_CUTOFF_TIME:
            break

        features = extract_features(daily_df, intraday_df, i)
        X = pd.DataFrame([features])[FEATURE_NAMES]
        call_proba = call_model.predict_proba(X)[0][1]
        put_proba = put_model.predict_proba(X)[0][1]

        price = intraday_df["close"].iloc[i]

        if call_proba >= call_threshold and put_proba < put_threshold:
            return Signal("CALL", timestamp, price, "ml", f"ML model confidence {call_proba:.2f} for CALL")
        if put_proba >= put_threshold and call_proba < call_threshold:
            return Signal("PUT", timestamp, price, "ml", f"ML model confidence {put_proba:.2f} for PUT")

    return Signal("NO_TRADE", None, None, None, "No ML prediction cleared its calibrated confidence threshold")


def main() -> None:
    daily_df = pd.read_csv(PROJECT_ROOT / "data" / "historical" / "NIFTY_50_day.csv")
    daily_df["date"] = pd.to_datetime(daily_df["date"])
    daily_df = daily_df.sort_values("date").reset_index(drop=True)

    intraday_df = pd.read_csv(PROJECT_ROOT / "data" / "historical" / "NIFTY_50_15minute.csv")
    intraday_df["date"] = pd.to_datetime(intraday_df["date"])
    intraday_df = intraday_df.sort_values("date").reset_index(drop=True)

    print("Building labeled dataset (this simulates every candle's hypothetical CALL and PUT outcome)...")
    labeled_df = build_labeled_dataset(daily_df, intraday_df)
    print(f"Labeled {len(labeled_df)} candles across {labeled_df['date'].nunique()} days.")
    print(f"Call win rate overall: {labeled_df['call_label'].mean():.1%} | Put win rate overall: {labeled_df['put_label'].mean():.1%}\n")

    train_df, test_df = time_based_split(labeled_df)
    print(f"Train: {train_df['date'].nunique()} days ({train_df['date'].min()} to {train_df['date'].max()})")
    print(f"Test:  {test_df['date'].nunique()} days ({test_df['date'].min()} to {test_df['date'].max()})\n")

    for model_type in MODEL_TYPES:
        print(f"--- Training {model_type} ---")
        call_model, put_model, call_threshold, put_threshold = train_models(train_df, model_type)
        save_models(model_type, call_model, put_model, call_threshold, put_threshold)
        print(f"Calibrated thresholds (from training data only): call={call_threshold:.2f}  put={put_threshold:.2f}")
        print(f"Models saved to {MODELS_DIR}\n")


if __name__ == "__main__":
    main()
